# .github/workflows/deploy.yml

name: CI/CD - Despliegue en VPS

on:
  push:
    branches:
      - main  # La rama que activará el despliegue

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Clonar el repositorio
        uses: actions/checkout@v4

      - name: 2. Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 3. Construir y subir la imagen de Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mi-app-next:latest # Cambia 'mi-app-next'

      - name: 4. Desplegar en el VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /ruta/a/tu/docker-compose
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mi-app-next:latest
            docker-compose up -d --no-build
            echo "¡Despliegue completado!"